# Generated by Django 4.0.4 on 2022-04-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_profile_slug_alter_profile_banner_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
