# Generated by Django 4.0.4 on 2022-04-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
