# Generated by Django 4.0.4 on 2022-04-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
